backend:
  name: git-gateway
  branch: master

media_folder: "static/media"
public_folder: "/media"
publish_mode: editorial_workflow

slug:
  encoding: ascii
  clean_accents: true

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template", name: "template", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string", required: false}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Image principale de l’article", name: "thumbnail", widget: "image", required: false}

  - name: "books"
    label: "Livres"
    folder: "content/books"
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    fields:
      - {label: "Template", name: "template", widget: "hidden", default: "book"}
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Auteur", name: "author", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Début de lecture", name: "readingStart", widget: "date"}
      - {label: "Fin de lecture", name: "readingEnd", widget: "date", required: false}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Catégorie", name: "category", widget: "string"}
      - {label: "Lien Amazon", name: "amazonLink", widget: "string"}
      - {label: "Contenu", name: "body", widget: "markdown", required: false}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Image du livre", name: "thumbnail", widget: "image", required: false}

  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template", name: "template", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Image principale de l’article", name: "thumbnail", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}